# Generated by Django 3.2.5 on 2022-07-11 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('instruments', models.TextField(max_length=100)),
                ('singer', models.BooleanField()),
                ('experience_level', models.TextField(max_length=100)),
                ('goals', models.TextField(max_length=100)),
                ('music_production_experience', models.BooleanField()),
                ('location', models.TextField(max_length=100)),
                ('associated_acts', models.TextField(max_length=100)),
                ('profile_text', models.TextField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
