# Generated by Django 3.2.5 on 2022-07-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.IntegerField(),
        ),
    ]
