# Generated by Django 3.2.5 on 2022-07-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_zip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(max_length=100),
        ),
    ]
