# Generated by Django 3.2.5 on 2022-07-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_location_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_zip',
        ),
    ]
