# Generated by Django 3.2.5 on 2022-07-22 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_location_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_zip',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
