# Generated by Django 3.2.5 on 2022-07-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_city',
            field=models.TextField(default='N/A', max_length=100),
        ),
    ]
