# Generated by Django 3.2.5 on 2022-07-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_location_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_city',
        ),
    ]
