# Generated by Django 3.2.5 on 2022-07-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_profile_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='associated_acts',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goals',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_text',
            field=models.TextField(max_length=500),
        ),
    ]
