# Generated by Django 3.2.5 on 2022-07-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='date',
            field=models.DateField(),
        ),
    ]
