# Generated by Django 3.2.5 on 2022-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_gig_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='singer_needed',
        ),
        migrations.AlterField(
            model_name='gig',
            name='instruments_needed',
            field=models.TextField(choices=[('Guitar', 'Guitar'), ('Bass', 'Bass'), ('Drums', 'Drums'), ('Keyboard', 'Keyboard')]),
        ),
    ]
