# Generated by Django 3.2.5 on 2022-07-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='ThreadModel',
        ),
    ]
